### ISSUE TITLE
Infinitly reforming reformed files

### ISSUE THREAD

**Issue by hendawy** [dropbox/pep8squad#1]
The app keeps on reforming and writing already reformed files, went into an inifnit loop.

![screenshot from 2015-04-09 12 36 48](https://cloud.githubusercontent.com/assets/4289297/7075360/2694de22-deb6-11e4-926b-9a419f04de70.png)

**Comment by ehfeng** [comment]
Can you upload the file that triggers this?

**Comment by hendawy** [comment]
I uploaded it publicly if that what you mean, there you go. https://dl.dropboxusercontent.com/u/45100125/lanterns.py

I think I know where the issue is, I forked, I will refactor and create a pulll request.

**Comment by hendawy** [comment]
Fixed
